name: SVN to Git Sync

on:
  schedule:
    - cron: '0 * * * *' # Adjust as necessary
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Install SVN and Git-SVN
        run: sudo apt-get update && sudo apt-get install -y subversion git-svn

      - name: Fetch latest SVN revision
        id: svnlog
        run: |
          LATEST_REVISION=$(svn log https://plugins.svn.wordpress.org/trusted-shops-easy-integration-for-woocommerce/ -l 1 | grep -oP '^r\K\d+')
          echo "LATEST_REVISION=$LATEST_REVISION" >> $GITHUB_ENV
          echo "::set-output name=revision::$LATEST_REVISION"

      - name: Clone SVN repository
        run: git svn clone --no-minimize-url -s -r${{ steps.svnlog.outputs.revision }} https://plugins.svn.wordpress.org/trusted-shops-easy-integration-for-woocommerce/ svn-repo

      - name: Change directory
        run: cd svn-repo

      - name: Fetch additional SVN data
        run: git svn fetch --log-window-size=10000

      - name: Rebase SVN changes
        run: git svn rebase

      - name: Commit changes to Git
        run: |
          cd svn-repo
          git config --global user.email "krystian.slowik@trustedshops.com"
          git config --global user.name "krystianslowik"
          git add .
          git commit -m "Sync SVN changes" || echo "No changes to commit"
          git push origin main

